version: "3.8"
name: base

services:
    proxy:
        container_name: bonsai-nginx-proxy-server
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/log.conf:/etc/nginx/log.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf.d/:/etc/nginx/conf.d/
            - /etc/letsencrypt/live/alemax.site/:/etc/nginx/
    # portainer:
    #     container_name: bonsai-portainer
    #     image: portainer/portainer-ce:latest
    #     ports:
    #         - 9443:9443
    #     volumes:
    #         - bonsai-v-portainer:/data
    #         - /var/run/docker.sock:/var/run/docker.sock
    #     restart: unless-stopped
# volumes:
# bonsai-v-portainer:
