version: "3.8"
name: home-lab-base

services:
    proxy:
        container_name: hl-nginx-proxy-server
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/log.conf:/etc/nginx/log.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf.d/:/etc/nginx/conf.d/
            - /etc/letsencrypt/live/alemax.site/fullchain.pem:/etc/nginx/fullchain.pem
            - /etc/letsencrypt/live/alemax.site/privkey.pem:/etc/nginx/privkey.pem
    containers-management:
        image: portainer/portainer-ce:latest
        ports:
            - 9443:9443
        volumes:
            - hl-v-portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
volumes:
    hl-v-portainer:
